[book]
authors = ["BonvinLab", "HADDOCK", "Computational Structural Biology", "Utrecht University"]
language = "en"
multilingual = false
src = "src"
title = "HADDOCK3 User Manual"

[output.html]
git-repository-url = "https://github.com/haddocking/haddock3-user-manual"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/haddocking/haddock3-user-manual/edit/main/{path}"
