name: build

on:
  pull_request:
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.47

    steps:
      - uses: actions/checkout@v4

      - run: rustup update stable && rustup default stable

      - run: cargo install --version ${MDBOOK_VERSION} mdbook

      - run: mdbook build
