name: lint

on:
  pull_request:
  workflow_dispatch: ~

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: "markdownlint.json"
          globs: "**/*.md"
